### ISSUE TITLE
Migrate to NWN: Enhanced Edition

### ISSUE THREAD

**Issue by zunath** [zunath/CyberpunkZombieSurvival_JVM#72]
Need to migrate the module and server to the Enhanced Edition.

This is dependent on a lot of things from the NWNX team - namely, the Java plugin. Cannot proceed with this until the NWNX_JVM plugin has been ported to EE.

**Comment by zunath** [comment]
Outstanding issues from the NWNX side:

- There are bugs with the Java plugin. Creator is looking into them this week.
- OnAttack event hook. I've got this coded but unable to test due to issues with the docker image. Waiting on that to be fixed by its maintainer.
- DM hooks: give/take XP, give/take levels, heal creature aren't ported to EE yet.
- SimTools hasn't been migrated to EE yet.
- Pause toggle event hook hasn't been migrated to EE yet.
- Unable to add custom item properties to items. This is in the old NWNX_Structs plugin which I've requested from the NWNX team.
- Need the BypassEvent method to be added to the events plugin.
- Need the conversation plugin migrated to EE.

A lot of these are critical to the migration and at the moment this item is stalled.

**Comment by zunath** [comment]
- Java plugin is working again from what I can tell. Need to do more thorough testing though.
- I added the OnAttack hook, but still need to do testing with the ranged combat system to be sure it works.
- No progress with DM hooks
- No progress with SimTools
- No progress with Pause toggle
- According to NWNX, the core needs additional functionality to push/pop custom item properties.
- No progress with the BypassEvent feature in the Events plugin.
- No progress with the conversation plugin. It may be possible to work around this using custom tokens, though.

**Comment by zunath** [comment]
Combat system seems to work fine now. Java appears to be good. I rewrote the conversation system to use regular NWN scripts. Also rewrote item durability system to not use item properties. Removed SimTools until it gets upgraded or I write my own chat command system.

Outstanding issues:

- Appears to be a problem with spawning zombies. Might be loot related based on the exception.
Exception:
```
Common.EventReceiver was unable to execute class method: Event.Area.OnEnter.runScript()
Exception:
java.lang.IllegalArgumentException: bound must be greater than origin
        at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:379)
        at GameSystems.SpawnSystem.CreateLoot(SpawnSystem.java:281)
        at GameSystems.SpawnSystem.OnAreaEnter(SpawnSystem.java:115)
        at Event.Area.OnEnter.runScript(OnEnter.java:28)
        at Common.EventReceiver.event(EventReceiver.java:20)
        at org.nwnx.nwnx2.jvm.Scheduler.event(Unknown Source)
```

- DM hooks need to be added to NWNX.
- BypassEvent is still missing (and a little too complicated for me to implement at the moment). So I'm working around it with ClearAllActions where possible.
- Pause toggle event needs to be added to NWNX.

The only critical issues we need to be EE-ready are the loot problems and the BypassEvent workaround. The rest we can deal with until NWNX supports them.

**Comment by zunath** [comment]
Fixed loot issue and added workarounds for BypassEvent. We're ready to start testing even though some features are missing.

Outstanding issues:

- DM hooks
- Pause toggle

**Comment by zunath** [comment]
I created another item for tracking DM Hooks and Pause toggling. Closing this item as the code has been merged.
